# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mapillary_traffic_signs
                                 A QGIS plugin
 This plugin allows for the usage of Mapillary traffic sign icons when using traffic sign data from mapillary.com
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-29
        copyright            : (C) 2025 by Gutingi
        email                : gutingi.dev@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mapillary_traffic_signs class from file mapillary_traffic_signs.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mapillary_ts import mapillary_traffic_signs
    return mapillary_traffic_signs(iface)
